language: ruby
sudo: false
rvm:
  - 2.2.2
script:
  - bundle exec rake spec
  - bundle exec teaspoon
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database test;' -U postgres
  - bundle exec rake db:migrate
addons:
  postgresql: "9.3"
env:
  FOG_DIRECTORY=empirical-core-travis-test
  PROGRESS_REPORT_FOG_DIRECTORY=empirical-progress-report-travis-test
